### ISSUE TITLE
Checkbox doesn't set isDirty

### ISSUE THREAD

**Issue by TRexStark** [skartknet/ConditionalDisplayers#14]
@skartknet

Hi Mario,

The Checkbox does not set the isDirty state and I tried to see how I can fix that given it's a uui component and there aren't many documentations out there, I couldn't figure it out.

I went as far as getting the property itself to be set from untouched to touched, but couldn't get the form to the state of 'Dirty'.

I will ask in discord for assistance, unless you know how this could be done?

**Comment by skartknet** [comment]
this is fixed on v3.3.1. The trick is to wrap the component in a `<ng-form>` and set the form dirty when the checkbox is touched with `$scope.modelValueForm.$setDirty();`

**Comment by TRexStark** [comment]
Awesome @skartknet - Genius! I thought that would be the case but just didn't have enough time to trial it.
