### ISSUE TITLE
Latest ConditionalDisplayers Checkbox is not compatible with Umbraco 8

### ISSUE THREAD

**Issue by robertjf** [skartknet/ConditionalDisplayers#27]
Due to the use of uUI, the Checkbox implementation (using uui-toggle) is not compatible with Umbraco 8 anymore.

I also know that in early versions of uUI, Safari had problems rendering the uui-toggle control - this may or may not be an issue depending on which version of Umbraco and consequently which version of uUI is in place.

**Comment by skartknet** [comment]
I should probably use different package version numbers for different Umbraco versions to make clear if they are supported or not, but I don't really intend to support every Umbraco version on every release. 

Not sure about the Safari issue, but I won't revert the UUI to support older Umbraco version. Unfortunately, the old Umbraco sites will miss any new features if they don't get upgraded.
