### ISSUE TITLE
Conditional Displayer Dropdown not loading properly on Server/app-service 

### ISSUE THREAD

**Issue by gurumurthyjv** [skartknet/ConditionalDisplayers#28]
Hi,

I was using Our.Umbraco.ConditionalDisplayers **v2.3.4** on Umbraco latest v8 and now migrated to V11.4.2, and installed with Our.Umbraco.ConditionalDisplayers **v3.4.0**, everything loads and works fine with my local laptop, but the same when deployed to Azure app service the datatype are not loading properly and even in content section the property not loads, along with an angular console error, attaching a screenshot.

**Error Screenshot from Server**
![ConditionalDisplayersError_SERVER](https://github.com/skartknet/ConditionalDisplayers/assets/36879551/2cef644d-f3ac-463b-bb45-123c9c61459a)

**No Error screenshot from local**
![ConditionalDisplayersError_LOCAL](https://github.com/skartknet/ConditionalDisplayers/assets/36879551/a9df3732-bd7a-45e1-a93f-8c9cd2f51b80)

Also, I see that from server url browser console source i dont see conditional displayers --> prevalueditors--> controller js file not loading
![image](https://github.com/skartknet/ConditionalDisplayers/assets/36879551/17145719-cc10-4fc5-8867-9d90dc2c5cf2)

**But the same loads in local**
![image](https://github.com/skartknet/ConditionalDisplayers/assets/36879551/968c2bbb-10ea-40b2-b38b-94920c0e590f)

**looking for some suggestions/help here or what's wrong am I doing** 

Thanks,
Gurumurthy JV

**Comment by TRexStark** [comment]
@gurumurthyjv in you csproj add the below and republish, test and see if that helps.
```
<ItemGroup>
    <Content Include="App_Plugins\**" CopyToOutputDirectory="Always" />
</ItemGroup>
```
