### ISSUE TITLE
Use Conditional Displayer when Extending MemberType

### ISSUE THREAD

**Issue by tekoscott** [skartknet/ConditionalDisplayers#3]
Hi,

I can successfully implement the conditional displayer package on a document type using a checkbox to hide o show a textbox. 

When I try to use it to hide or show a textbox using a checkbox on a membertype it does not work?

My question is, can the Conditional Displayer package be used to hide or show fields when extending the MemberType?

Kind Regards
Scott

**Comment by skartknet** [comment]
Hi @tekoscott , apologies but this issue fell off my radar. Hopefully, you fixed your problem. Actually, it looks like the package doesn't work with member types. Never realised about that before.

**Comment by skartknet** [comment]
This seems to be a bug on Umbraco. The `data-element` attribute is repeated. This alias is used by CD to target each property.
![image](https://user-images.githubusercontent.com/1685262/209434272-07a41604-0e16-4eda-9078-31e30002b596.png)

**Comment by skartknet** [comment]
I have opened a ticket and created a PR to fix it: https://github.com/umbraco/Umbraco-CMS/issues/13619

**Comment by tekoscott** [comment]
Apologies for not getting back sooner. Thanks for that.
