### ISSUE TITLE
Seems to work when editing the document type but not when editing the page?

### ISSUE THREAD

**Issue by gsidoel** [skartknet/ConditionalDisplayers#6]
Hi, thanks for a great package.
I have installed v2.3.4 on umbraco 8.18.5 as a package. I have created a checkbox conditional. When I add this conditional to the document type, I see the targeted properties get hidden. But when I edit the page where this document type is used, it has no effect. Is 8.18 not supported?

**Comment by skartknet** [comment]
Hi @gsidoel , have you tried with the latest version 3.2.0?

**Comment by skartknet** [comment]
I'll close this for now as I can't reproduce. If you have more info on how to reproduce please let me know.
